/**
 * Complaint Model
 * 
 * Interacts with Supabase 'complaints' table.
 * 
 * -- SQL Schema for Supabase --
 * 
 * CREATE TABLE complaints (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   email TEXT NOT NULL,
 *   phone TEXT NOT NULL,
 *   category TEXT NOT NULL,
 *   description TEXT NOT NULL,
 *   location TEXT NOT NULL,
 *   priority TEXT DEFAULT 'Medium' NOT NULL CHECK (priority IN ('Low', 'Medium', 'High')),
 *   status TEXT DEFAULT 'Pending' NOT NULL CHECK (status IN ('Pending', 'In Progress', 'Resolved')),
 *   created_at TIMESTAMPTZ DEFAULT now() NOT NULL
 * );
 */

const supabase = require('../config/db');

class Complaint {
  /**
   * Save a new complaint to Supabase
   * @param {Object} data - Complaint data
   * @returns {Promise<Object>} The inserted complaint record
   */
  static async create(data) {
    const { data: record, error } = await supabase
      .from('complaints')
      .insert([
        {
          name: data.name,
          email: data.email,
          phone: data.phone,
          category: data.category,
          description: data.description,
          location: data.location,
          priority: data.priority || 'Medium',
          status: data.status || 'Pending'
        }
      ])
      .select()
      .single();

    if (error) {
      throw error;
    }
    return record;
  }

  /**
   * Fetch all complaints with optional filtering, search, and sorting
   * @param {Object} filters - Search, filter, and sort options
   * @returns {Promise<Array>} List of complaints
   */
  static async findAll({ search, status, sort }) {
    let query = supabase.from('complaints').select('*');

    // Status Filter
    if (status && status !== 'All') {
      query = query.eq('status', status);
    }

    // Search Filter (Search name, category, or location)
    if (search && search.trim() !== '') {
      const sanitizedSearch = search.trim();
      query = query.or(
        `name.ilike.%${sanitizedSearch}%,category.ilike.%${sanitizedSearch}%,location.ilike.%${sanitizedSearch}%`
      );
    }

    // Sort Options
    if (sort === 'oldest') {
      query = query.order('created_at', { ascending: true });
    } else {
      // Default: Newest first
      query = query.order('created_at', { ascending: false });
    }

    const { data, error } = await query;

    if (error) {
      throw error;
    }
    return data || [];
  }

  /**
   * Find a single complaint by its ID
   * @param {string|number} id - Complaint ID
   * @returns {Promise<Object|null>} Complaint record or null
   */
  static async findById(id) {
    const { data, error } = await supabase
      .from('complaints')
      .select('*')
      .eq('id', id)
      .maybeSingle(); // Prevents throwing if record not found

    if (error) {
      throw error;
    }
    return data;
  }

  /**
   * Update complaint by ID
   * @param {string|number} id - Complaint ID
   * @param {Object} updateData - Updated fields
   * @returns {Promise<Object>} Updated record
   */
  static async update(id, updateData) {
    const cleanUpdate = {};
    const allowedFields = ['name', 'email', 'phone', 'category', 'description', 'location', 'priority', 'status'];
    
    allowedFields.forEach(field => {
      if (updateData[field] !== undefined) {
        cleanUpdate[field] = updateData[field];
      }
    });

    const { data, error } = await supabase
      .from('complaints')
      .update(cleanUpdate)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      throw error;
    }
    return data;
  }

  /**
   * Delete complaint by ID
   * @param {string|number} id - Complaint ID
   * @returns {Promise<boolean>} True if deleted successfully
   */
  static async delete(id) {
    const { error } = await supabase
      .from('complaints')
      .delete()
      .eq('id', id);

    if (error) {
      throw error;
    }
    return true;
  }

  /**
   * Get complaints statistics (Total, Status counts, High priority count)
   * @returns {Promise<Object>} Dashboard stats
   */
  static async getStats() {
    // Run queries in parallel to get count aggregates
    const [
      { count: totalCount, error: errTotal },
      { count: pendingCount, error: errPending },
      { count: inProgressCount, error: errInProgress },
      { count: resolvedCount, error: errResolved },
      { count: highPriorityCount, error: errHigh }
    ] = await Promise.all([
      supabase.from('complaints').select('*', { count: 'exact', head: true }),
      supabase.from('complaints').select('*', { count: 'exact', head: true }).eq('status', 'Pending'),
      supabase.from('complaints').select('*', { count: 'exact', head: true }).eq('status', 'In Progress'),
      supabase.from('complaints').select('*', { count: 'exact', head: true }).eq('status', 'Resolved'),
      supabase.from('complaints').select('*', { count: 'exact', head: true }).eq('priority', 'High')
    ]);

    if (errTotal || errPending || errInProgress || errResolved || errHigh) {
      throw errTotal || errPending || errInProgress || errResolved || errHigh;
    }

    return {
      total: totalCount || 0,
      pending: pendingCount || 0,
      inProgress: inProgressCount || 0,
      resolved: resolvedCount || 0,
      highPriority: highPriorityCount || 0
    };
  }
}

module.exports = Complaint;
